from app import create_app
from app.models import db, User, Topic, Word, WordProgress
from werkzeug.security import generate_password_hash
from datetime import datetime, timezone, timedelta
import random

app = create_app()


def seed_database():
    with app.app_context():
        db.drop_all()
        db.create_all()

        now = datetime.now(timezone.utc)

        users = [
            {'user': 'admin', 'pass': 'admin', 'is_admin': True},
            {'user': 'testuser', 'pass': 'password123', 'is_admin': False},
            {'user': 'study_champ', 'pass': 'password123', 'is_admin': False},
            {'user': 'vocab_master', 'pass': 'password123', 'is_admin': False}
        ]

        user_objects = {}
        for u in users:
            hashed = generate_password_hash(u['pass'], method='pbkdf2:sha256')
            new_user = User(username=u['user'], password_hash=hashed, is_admin=u['is_admin'])
            db.session.add(new_user)
            db.session.commit()
            user_objects[u['user']] = new_user

        main_user = user_objects['testuser']
        champ = user_objects['study_champ']
        master = user_objects['vocab_master']

        vocab_data = {
            "Java Programming": [
                ("JVM", "ˌdʒeɪ viː ˈem", "Java Virtual Machine that executes bytecode.",
                 "The JVM allows Java to run on any operating system."),
                ("Polymorphism", "ˌpɑːliˈmɔːrfɪzəm", "The ability of an object to take on many forms.",
                 "Method overriding is an example of runtime polymorphism."),
                ("Encapsulation", "ɪnˌkæpsəˈleɪʃən", "Wrapping code and data together into a single unit.",
                 "Using private variables with public getters provides encapsulation."),
                ("Inheritance", "ɪnˈherɪtəns", "Mechanism where one class acquires the properties of another.",
                 "The dog class uses inheritance to get traits from the animal class."),
                ("Abstract Class", "ˈæbstrækt klæs", "A restricted class that cannot be used to create objects.",
                 "We created an abstract class for the base game entity."),
                ("Interface", "ˈɪntərfeɪs", "A completely abstract class used to group related methods.",
                 "The class implements the runnable interface."),
                ("Garbage Collection", "ˈɡɑːrbɪdʒ kəˈlekʃən", "Automatic memory management process.",
                 "Garbage collection frees up memory taken by unreachable objects."),
                ("Thread", "θred", "The smallest unit of processing that can be scheduled.",
                 "We spawned a new thread to handle the background download."),
                ("Exception", "ɪkˈsepʃən", "An unwanted event that interrupts the normal flow of the program.",
                 "The try-catch block handles the exception."),
                ("NullPointerException", "nʌl ˈpɔɪntər ɪkˈsepʃən",
                 "Error thrown when an application attempts to use null.",
                 "A NullPointerException crashed the app because the object wasn't instantiated."),
                ("Generics", "dʒəˈnerɪks", "Enables types to be parameters when defining classes.",
                 "Generics ensure compile-time safety for the ArrayList."),
                ("Lambda Expression", "ˈlæmdə ɪkˈspreʃən",
                 "A short block of code which takes parameters and returns a value.",
                 "We used a lambda expression to sort the list quickly."),
                ("Stream API", "striːm ˌeɪ piː ˈaɪ", "Used to process collections of objects in a functional style.",
                 "The stream API filtered out all the empty strings."),
                ("Maven", "ˈmeɪvən", "A build automation tool used primarily for Java projects.",
                 "Maven downloaded all the necessary dependencies."),
                ("JAR", "dʒɑːr", "A package file format typically used to aggregate many Java class files.",
                 "We exported the application as an executable JAR file."),
                ("Spring Boot", "sprɪŋ buːt", "An open-source Java-based framework to create microservices.",
                 "Spring Boot made setting up the REST API incredibly fast."),
                ("Constructor", "kənˈstrʌktər", "A special method used to initialize objects.",
                 "The constructor sets the initial hit points for the enemy."),
                ("Static Keyword", "ˈstætɪk ˈkiːwɜːrd",
                 "Indicates that the particular member belongs to a type itself.",
                 "A static method can be called without creating an instance."),
                ("Final Keyword", "ˈfaɪnəl ˈkiːwɜːrd", "A non-access modifier used to restrict the user.",
                 "A final variable acts as a constant."),
                ("Wrapper Class", "ˈræpər klæs", "Provides a way to use primitive data types as objects.",
                 "Integer is the wrapper class for the primitive int type.")
            ],
            "Python Programming": [
                ("List Comprehension", "lɪst ˌkɑːmprɪˈhenʃən", "A concise way to create lists.",
                 "We used list comprehension to square all numbers in the array."),
                ("Decorator", "ˈdekəreɪtər", "A function that takes another function and extends its behavior.",
                 "The @login_required decorator protects the route."),
                ("Generator", "ˈdʒenəreɪtər", "A function that returns an iterator that produces a sequence of values.",
                 "The generator yields one large file chunk at a time."),
                ("Tuple", "ˈtʌpəl", "A collection which is ordered and unchangeable.",
                 "We stored the coordinates as a tuple."),
                ("Dictionary", "ˈdɪkʃəneri", "A collection which is ordered, changeable and do not allow duplicates.",
                 "The dictionary mapped usernames to their high scores."),
                ("PEP 8", "pep eɪt", "The style guide for Python code.",
                 "Running the linter ensured our code was PEP 8 compliant."),
                ("GIL", "ɡɪl", "Global Interpreter Lock that prevents multiple native threads from executing.",
                 "The GIL can be a bottleneck in CPU-bound Python programs."),
                ("Virtual Environment", "ˈvɜːrtʃuəl ɪnˈvaɪrənmənt", "An isolated workspace for Python projects.",
                 "Always activate your virtual environment before pip installing."),
                ("NumPy", "ˈnʌmpaɪ", "A library used for working with arrays.",
                 "NumPy makes complex matrix math highly efficient."),
                ("Pandas", "ˈpændəz", "A software library for data manipulation and analysis.",
                 "We used Pandas to read the massive CSV file into a DataFrame."),
                ("Indentation", "ˌɪndenˈteɪʃən", "The spaces at the beginning of a code line.",
                 "Python uses indentation to indicate a block of code."),
                ("Dunder Methods", "ˈdʌndər ˈmeθədz", "Special methods with double underscores.",
                 "We overrode the __str__ dunder method to format the output."),
                ("Slicing", "ˈslaɪsɪŋ", "Extracting a particular set of elements from a string or list.",
                 "List slicing let us grab the first five elements easily."),
                ("F-String", "ef strɪŋ", "String literals that have an f at the beginning and curly braces.",
                 "The f-string made inserting variables into the text much cleaner."),
                ("Yield", "jiːld", "A keyword used in Python to return a generator.",
                 "Using yield instead of return saved a lot of memory."),
                ("Self", "self", "Represents the instance of the class.",
                 "You must pass self as the first parameter of instance methods."),
                ("Pass Keyword", "pæs ˈkiːwɜːrd", "A null statement used as a placeholder.",
                 "I put a pass keyword in the empty function to prevent an error."),
                ("Set", "set", "A collection which is unordered, unchangeable, and unindexed.",
                 "Converting the list to a set quickly removed all duplicates."),
                ("Kwargs", "kwɑːrɡz", "Allows passing a variable number of keyword arguments.",
                 "We used **kwargs to handle optional configuration parameters."),
                ("Pip", "pɪp", "The package installer for Python.", "We ran pip to install the Flask framework.")
            ],
            "SQL & Databases": [
                ("Primary Key", "ˈpraɪmeri kiː",
                 "A specific choice of a minimal set of attributes that uniquely specify a tuple.",
                 "The user ID serves as the primary key for the table."),
                ("Foreign Key", "ˈfɔːrən kiː", "A field in one table that uniquely identifies a row of another table.",
                 "The topic_id acts as a foreign key linking words to topics."),
                ("INNER JOIN", "ˈɪnər dʒɔɪn", "Selects records that have matching values in both tables.",
                 "An INNER JOIN combined the user data with their order history."),
                ("Index", "ˈɪndeks", "A data structure that improves the speed of data retrieval operations.",
                 "Adding an index to the email column drastically sped up login times."),
                ("Normalization", "ˌnɔːrmələˈzeɪʃən", "The process of organizing data to reduce redundancy.",
                 "Database normalization split our massive table into three smaller ones."),
                ("ACID", "ˈæsɪd", "Properties of database transactions: Atomicity, Consistency, Isolation, Durability.",
                 "ACID compliance ensures financial transactions are processed reliably."),
                ("Transaction", "trænˈzækʃən", "A logical unit of work that contains one or more SQL statements.",
                 "If the payment fails, the transaction is rolled back."),
                ("View", "vjuː", "A virtual table based on the result-set of an SQL statement.",
                 "We created a view to simplify querying the complex reporting metrics."),
                ("Trigger", "ˈtrɪɡər", "A stored procedure that automatically runs when an event occurs.",
                 "A trigger automatically updates the timestamp when a row is modified."),
                ("Stored Procedure", "stɔːrd prəˈsiːdʒər", "Prepared SQL code that you can save and reuse.",
                 "Calling the stored procedure reduced network traffic between the app and the database."),
                ("GROUP BY", "ɡruːp baɪ", "Groups rows that have the same values into summary rows.",
                 "We used GROUP BY to count how many users live in each city."),
                ("HAVING", "ˈhævɪŋ", "Added to SQL because the WHERE keyword cannot be used with aggregate functions.",
                 "The HAVING clause filtered the groups to only show those with more than 10 members."),
                ("Subquery", "ˈsʌbkwɪri", "A query nested inside another query.",
                 "The subquery found the average price before the main query filtered the items."),
                ("DDL", "ˌdiː diː ˈel", "Data Definition Language, used to define database structures.",
                 "CREATE and DROP are examples of DDL commands."),
                ("DML", "ˌdiː em ˈel", "Data Manipulation Language, used to manage data within schema objects.",
                 "INSERT and UPDATE are examples of DML commands."),
                ("NoSQL", "noʊ ˈsiːkwəl",
                 "Database provides a mechanism for storage and retrieval of data that is modeled in means other than tabular.",
                 "MongoDB is a popular NoSQL database system."),
                ("B-Tree", "ˈbiː triː", "A self-balancing tree data structure that maintains sorted data.",
                 "Most relational databases use B-Trees for their default indexing."),
                ("Deadlock", "ˈdedlɑːk",
                 "A situation where two or more transactions are waiting for one another to give up locks.",
                 "The database engine aborted one transaction to resolve the deadlock."),
                ("ORM", "ˌoʊ ɑːr ˈem", "Object-Relational Mapping, a programming technique for converting data.",
                 "SQLAlchemy is the ORM we use to interact with the database in Python."),
                ("Query Optimization", "ˈkwɪri ˌɑːptɪməˈzeɪʃən",
                 "The process of selecting the most efficient execution plan.",
                 "Query optimization reduced the search time from seconds to milliseconds.")
            ],
            "AI & Large Language Models": [
                ("Neural Network", "ˈnʊrəl ˈnetwɜːrk", "Computing systems inspired by the biological neural networks.",
                 "The neural network was trained to recognize handwritten digits."),
                ("Token", "ˈtoʊkən", "The basic unit of data processed by an LLM.",
                 "The prompt was split into 50 tokens before being fed to the model."),
                ("Attention Mechanism", "əˈtenʃən ˈmekənɪzəm",
                 "Allows models to focus on specific parts of the input sequence.",
                 "The attention mechanism helped the model understand the context of the ambiguous word."),
                ("Transformer", "trænsˈfɔːrmər", "A deep learning architecture based on attention mechanisms.",
                 "The Transformer architecture revolutionalized natural language processing."),
                ("Fine-tuning", "faɪn ˈtuːnɪŋ",
                 "Taking a pre-trained model and training it further on a specific dataset.",
                 "We are fine-tuning the LLM on our internal company documents."),
                ("Prompt Engineering", "prɑːmpt ˌendʒɪˈnɪrɪŋ",
                 "The practice of designing inputs to guide an AI to produce optimal outputs.",
                 "Good prompt engineering drastically reduced the model's errors."),
                ("Hallucination", "həˌluːsɪˈneɪʃən",
                 "When an AI model generates false or illogical information confidently.",
                 "The model experienced a hallucination and invented a fake historical event."),
                ("Embedding", "ɪmˈbedɪŋ", "A dense vector representation of data in a continuous vector space.",
                 "Word embeddings capture the semantic meaning of vocabulary."),
                ("Gradient Descent", "ˈɡreɪdiənt dɪˈsent",
                 "An optimization algorithm used to minimize the loss function.",
                 "Gradient descent slowly adjusted the model's weights during training."),
                ("Backpropagation", "ˌbækprɑːpəˈɡeɪʃən",
                 "The algorithm used to calculate derivatives of the error function.",
                 "Backpropagation is essential for training deep neural networks."),
                ("Overfitting", "ˌoʊvərˈfɪtɪŋ",
                 "When a model learns the training data too well and performs poorly on new data.",
                 "Adding dropout layers helped prevent the model from overfitting."),
                ("Epoch", "ˈepək", "One complete pass of the training dataset through the algorithm.",
                 "The model accuracy plateaued after 50 epochs."),
                ("Batch Size", "bætʃ saɪz", "The number of training examples utilized in one iteration.",
                 "A smaller batch size consumes less memory but takes longer to train."),
                ("Weights", "weɪts", "Parameters within a neural network that transform input data.",
                 "The weights are adjusted continuously during the training phase."),
                ("Activation Function", "ˌæktɪˈveɪʃən ˈfʌŋkʃən",
                 "Defines the output of a neural network node given an input.",
                 "ReLU is a highly popular activation function in deep learning."),
                ("RAG", "ræɡ", "Retrieval-Augmented Generation, combining search with LLM generation.",
                 "RAG prevents hallucinations by grounding the AI in factual documents."),
                ("Zero-shot Learning", "ˈzɪroʊ ʃɑːt ˈlɜːrnɪŋ",
                 "A model's ability to perform a task without having seen any examples.",
                 "The LLM translated the text perfectly using zero-shot learning."),
                ("Inference", "ˈɪnfərəns", "The process of using a trained model to make predictions.",
                 "Optimizing the code reduced inference time to under 100 milliseconds."),
                ("Context Window", "ˈkɑːntekst ˈwɪndoʊ", "The maximum amount of text an LLM can process at one time.",
                 "The new model boasts a massive context window of one million tokens."),
                ("Temperature", "ˈtemprətʃər", "A parameter that controls the randomness of an AI's responses.",
                 "Setting the temperature to zero makes the model's output highly deterministic.")
            ],
            "VR & Unity Development": [
                ("Prefab", "ˈpriːfæb", "A reusable GameObject asset.",
                 "We instantiated the enemy prefab whenever the spawner triggered."),
                ("Rigidbody", "ˈrɪdʒɪdbɑːdi", "A component that puts a GameObject under the control of physics.",
                 "Adding a Rigidbody allowed the virtual ball to bounce and roll."),
                ("Collider", "kəˈlaɪdər", "Defines the physical boundaries of a GameObject for collisions.",
                 "The box collider ensured the player couldn't walk through the wall."),
                ("Mesh", "meʃ", "The structural build of a 3D model consisting of polygons.",
                 "The character mesh was incredibly detailed with thousands of vertices."),
                ("Quaternion", "kwəˈtɜːrniən", "A mathematical construct used to represent rotations.",
                 "Unity uses Quaternions to avoid gimbal lock when rotating objects."),
                ("Raycast", "ˈreɪkæst", "Projecting a line through space to detect intersections with colliders.",
                 "We used a raycast to determine if the player's gun was aiming at an enemy."),
                ("Transform", "trænsˈfɔːrm",
                 "A component that determines the Position, Rotation, and Scale of an object.",
                 "Every object in a Unity scene has a Transform component attached."),
                ("MonoBehaviour", "ˈmɑːnoʊbɪˌheɪvjər", "The base class from which every Unity script derives.",
                 "Our custom player controller script inherited from MonoBehaviour."),
                ("Material", "məˈtɪriəl", "Defines how a surface should be rendered.",
                 "The metallic material made the robot look shiny and reflective."),
                ("Shader", "ˈʃeɪdər", "A script that contains mathematical calculations and algorithms for rendering.",
                 "The custom water shader simulated realistic waves and light refraction."),
                ("Frame Rate", "freɪm reɪt", "The frequency at which consecutive images are displayed.",
                 "VR applications must maintain a high frame rate to prevent motion sickness."),
                ("Field of View", "fiːld əv vjuː",
                 "The extent of the observable world that is seen at any given moment.",
                 "Increasing the field of view made the VR headset feel more immersive."),
                ("HMD", "ˌeɪtʃ em ˈdiː", "Head-Mounted Display, the hardware worn on the head for VR.",
                 "The HMD tracked the user's head movements with zero latency."),
                ("Tracking", "ˈtrækɪŋ", "Monitoring the position and orientation of VR hardware in physical space.",
                 "Inside-out tracking uses cameras on the headset itself."),
                ("Latency", "ˈleɪtənsi", "The time delay between a physical movement and the visual update.",
                 "High latency ruins the illusion of virtual reality."),
                ("Render Pipeline", "ˈrendər ˈpaɪplaɪn",
                 "A series of steps that take a scene and display it on screen.",
                 "We switched to the Universal Render Pipeline to improve mobile performance."),
                ("Scene", "siːn", "A container that holds all the objects and environments for a level.",
                 "Loading the next scene seamlessly was a major technical challenge."),
                ("Coroutine", "koʊruːˈtiːn", "A function that can pause execution and return control to Unity.",
                 "The coroutine faded the screen to black over three seconds."),
                ("Asset", "ˈæset", "Any media or data that can be used in your game.",
                 "The Unity Asset Store is full of free 3D models and sound effects."),
                ("Canvas", "ˈkænvəs", "The root component for all UI elements in Unity.",
                 "We placed the health bar and score counter onto the main Canvas.")
            ],
            "PC Building & Architecture": [
                ("Motherboard", "ˈmʌðərbɔːrd",
                 "The main printed circuit board found in general purpose microcomputers.",
                 "The motherboard connects the CPU, memory, and all peripheral devices."),
                ("CPU", "ˌsiː piː ˈjuː", "Central Processing Unit, the primary component that acts as the brain.",
                 "The new CPU has 16 cores and handles multitasking effortlessly."),
                ("GPU", "ˌdʒiː piː ˈjuː",
                 "Graphics Processing Unit, specialized electronic circuit for image rendering.",
                 "An RTX GPU is essential for modern gaming and machine learning tasks."),
                ("RAM", "ræm", "Random Access Memory, a form of volatile computer memory.",
                 "Upgrading to 32GB of RAM allowed the IDE and multiple browser tabs to run smoothly."),
                ("PSU", "ˌpiː es ˈjuː", "Power Supply Unit, converts mains AC to low-voltage regulated DC power.",
                 "A reliable PSU is critical to prevent hardware failure under heavy loads."),
                ("NVMe", "ˌen viː em ˈiː", "Non-Volatile Memory Express, a protocol for accessing high-speed storage.",
                 "Installing an NVMe drive reduced the operating system boot time to seconds."),
                ("Thermal Paste", "ˈθɜːrməl peɪst",
                 "A thermally conductive compound placed between heat sinks and heat sources.",
                 "Applying fresh thermal paste lowered the processor's running temperature."),
                ("Heatsink", "ˈhiːtsɪŋk",
                 "A passive heat exchanger that transfers heat generated by an electronic device.",
                 "The massive copper heatsink kept the system completely silent."),
                ("BIOS", "ˈbaɪoʊs", "Basic Input/Output System, firmware used to perform hardware initialization.",
                 "You need to enter the BIOS to change the boot order of your drives."),
                ("Overclocking", "ˌoʊvərˈklɑːkɪŋ",
                 "Configuring a component to run faster than the manufacturer's specified speed.",
                 "Overclocking the GPU gave a noticeable boost in frame rates."),
                ("Arch Linux", "ɑːrtʃ ˈlɪnəks", "A lightweight and flexible Linux distribution.",
                 "Installing Arch Linux requires using the command line manually."),
                ("Kernel", "ˈkɜːrnəl", "The core component of an operating system.",
                 "The Linux kernel manages the communication between hardware and software."),
                ("Shell", "ʃel", "A user interface for access to an operating system's services.",
                 "We wrote a bash script to run in the shell and automate backups."),
                ("Root", "ruːt", "The superuser account in Unix-like operating systems.",
                 "You need root privileges to install software system-wide."),
                ("Package Manager", "ˈpækɪdʒ ˈmænɪdʒər",
                 "A collection of software tools that automate installing and upgrading software.",
                 "Pacman is the default package manager for Arch Linux."),
                ("GRUB", "ɡrʌb", "A boot loader package from the GNU Project.",
                 "GRUB allowed the user to dual-boot between Linux and Windows."),
                ("Systemd", "ˈsɪstəm diː", "A software suite that provides an array of system components for Linux.",
                 "We used systemd to ensure the web server automatically restarts on crash."),
                ("Bash", "bæʃ", "A Unix shell and command language.",
                 "Bash is the default shell on most modern Linux distributions."),
                ("Mounting", "ˈmaʊntɪŋ", "The process of making a file system accessible.",
                 "Mounting the USB drive allowed us to copy the files over."),
                ("Swap", "swɑːp", "Space on a hard disk used as the virtual memory extension.",
                 "The system used swap space when it completely ran out of physical RAM.")
            ],
            "Football": [
                ("Offside", "ˌɔːfˈsaɪd",
                 "When an attacking player is closer to the opponent's goal line than both the ball and the second-last opponent.",
                 "The striker's goal was disallowed because he was clearly offside."),
                ("Pitch", "pɪtʃ", "The playing surface for a game of association football.",
                 "The grass on the pitch was slick after the heavy rain."),
                ("Clean Sheet", "kliːn ʃiːt", "When a goalkeeper or team prevents the opponent from scoring any goals.",
                 "The defender celebrated keeping a clean sheet in the crucial final match."),
                ("Hat-trick", "ˈhæt trɪk", "When a single player scores three goals in a single game.",
                 "He took the match ball home after scoring a brilliant hat-trick."),
                ("Penalty", "ˈpenəlti", "A free kick taken from the penalty spot, 12 yards from the goal.",
                 "The referee awarded a penalty after the foul inside the box."),
                ("Corner Kick", "ˈkɔːrnər kɪk",
                 "A restart of play awarded to the attacking team when the ball leaves the field across the goal line.",
                 "The tall defender headed the ball in directly from the corner kick."),
                ("Free Kick", "friː kɪk", "A method of restarting play awarded following a foul.",
                 "He curled the free kick perfectly over the wall and into the top corner."),
                ("VAR", "ˌviː eɪ ˈɑːr",
                 "Video Assistant Referee, an official who reviews decisions made by the head referee.",
                 "VAR overturned the decision and awarded the goal."),
                ("Striker", "ˈstraɪkər", "An attacking player whose primary role is to score goals.",
                 "The team bought a new striker to solve their goal-scoring issues."),
                ("Midfielder", "ˈmɪdfiːldər",
                 "Players whose general position of play is between the attackers and defenders.",
                 "The central midfielder dictated the tempo of the entire game."),
                ("Defender", "dɪˈfendər", "A player whose primary role is to stop attacks during the game.",
                 "The defender made a crucial sliding tackle to stop the breakaway."),
                ("Goalkeeper", "ˈɡoʊlˌkiːpər",
                 "The player positioned directly in front of the goal whose main job is to stop the ball.",
                 "The goalkeeper made a spectacular diving save."),
                ("Red Card", "red kɑːrd", "Shown by the referee to indicate a player is sent off the field.",
                 "The aggressive tackle immediately earned him a red card."),
                ("Yellow Card", "ˈjeloʊ kɑːrd", "Shown by the referee as a caution to a player.",
                 "Accumulating two yellow cards in one game results in an automatic dismissal."),
                ("Tackle", "ˈtækəl", "The act of taking the ball away from an opposing player.",
                 "His perfectly timed tackle stopped a dangerous counter-attack."),
                ("Dribbling", "ˈdrɪblɪŋ", "Moving the ball past opponents while retaining possession.",
                 "Her skillful dribbling left three defenders on the ground."),
                ("Cross", "krɔːs", "A medium- to-long-range pass from a wide area of the pitch towards the centre.",
                 "The winger delivered a beautiful cross into the penalty area."),
                ("Header", "ˈhedər", "A technique of playing the ball using the head.",
                 "He scored a powerful header to tie the game in the final minute."),
                ("Extra Time", "ˈekstrə taɪm", "Additional time played when a knockout match ends in a draw.",
                 "Both teams looked exhausted during the thirty minutes of extra time."),
                ("Old Trafford", "oʊld ˈtræfərd", "A football stadium in Greater Manchester, England.",
                 "Old Trafford is famously known as the Theatre of Dreams.")
            ],
            "Video Gaming": [
                ("FPS", "ˌef piː ˈes", "First-Person Shooter or Frames Per Second.",
                 "The game runs at a smooth 144 FPS on the new monitor."),
                ("Ping", "pɪŋ", "The network latency between a player's client and the game server.",
                 "High ping made the game lag and register hits late."),
                ("Hitbox", "ˈhɪtbɑːks",
                 "An invisible shape commonly used in video games for real-time collision detection.",
                 "The sniper rifle missed because the character's hitbox was smaller than the model."),
                ("Respawn", "ˌriːˈspɔːn", "The recreation of an entity after its death or destruction.",
                 "Players have to wait ten seconds to respawn after being eliminated."),
                ("Loot", "luːt", "Items collected by the player in the game.",
                 "Defeating the dragon dropped some incredibly rare epic loot."),
                ("NPC", "ˌen piː ˈsiː", "Non-Player Character, any character not controlled by a human.",
                 "The NPC gave the player a map to the hidden dungeon."),
                ("Quest", "kwest",
                 "A task in a video game that a player character may complete in order to gain a reward.",
                 "Completing the side quest unlocked a unique weapon."),
                ("Boss", "bɔːs", "A significantly powerful computer-controlled enemy.",
                 "The final boss required perfect timing to defeat."),
                ("Cooldown", "ˈkuːldaʊn",
                 "The minimum length of time that the player needs to wait after using an ability.",
                 "You can't use your ultimate ability while it is on cooldown."),
                ("DPS", "ˌdiː piː ˈes", "Damage Per Second, a measure of the damage dealt in games.",
                 "The rogue class has the highest single-target DPS in the group."),
                ("HUD", "hʌd", "Heads-Up Display, the method by which information is visually relayed to the player.",
                 "The HUD displays the player's remaining health and ammo."),
                ("Matchmaking", "ˈmætʃmeɪkɪŋ", "The process of connecting players together for online play.",
                 "Skill-based matchmaking ensures games are competitive and fair."),
                ("Meta", "ˈmetə", "The most effective tactics available in the current state of the game.",
                 "Using assault rifles is the current meta after the latest patch."),
                ("Nerf", "nɜːrf", "A change made to a game to reduce the power of a weapon or ability.",
                 "The developers decided to nerf the overly powerful shotgun."),
                ("Buff", "bʌf", "A change made to a game to increase the power of a weapon or ability.",
                 "The healing spell received a buff to make it more viable."),
                ("Camper", "ˈkæmpər",
                 "A player who remains in one spot for an extended period to gain a tactical advantage.",
                 "A sniper camper was hiding in the tower the entire match."),
                ("Grind", "ɡraɪnd", "Performing repetitive tasks for gameplay advantage or loot.",
                 "Reaching the maximum level requires a significant amount of grinding."),
                ("Speedrun", "ˈspiːdrʌn", "A playthrough of a video game completed as fast as possible.",
                 "The new world record speedrun skipped three major levels."),
                ("Easter Egg", "ˈiːstər eɡ", "An intentional inside joke, hidden message, or feature.",
                 "Finding the hidden developer room was a fun easter egg."),
                ("Agro", "ˈæɡroʊ", "To draw the hostility of enemies in a video game.",
                 "The heavily armored tank pulled agro so the healers wouldn't be attacked.")
            ],
            "Software Engineering": [
                ("Agile", "ˈædʒaɪl", "A set of frameworks and practices based on the values of the Agile Manifesto.",
                 "The team uses Agile methodologies to quickly adapt to changing requirements."),
                ("Scrum", "skrʌm", "An agile framework that helps teams work together.",
                 "We hold a daily scrum meeting to discuss progress and blockers."),
                ("Version Control", "ˈvɜːrʒən kənˈtroʊl",
                 "The practice of tracking and managing changes to software code.",
                 "Using version control allowed us to revert a breaking change immediately."),
                ("Git", "ɡɪt", "A distributed version control system.",
                 "We created a new git branch to isolate the experimental feature."),
                ("Commit", "kəˈmɪt", "Recording changes to the repository.",
                 "Always write clear, descriptive messages when you make a new commit."),
                ("Push", "pʊʃ", "Uploading local repository content to a remote repository.",
                 "Remember to push your code before leaving for the day."),
                ("Pull Request", "pʊl rɪˈkwest", "A method of submitting contributions to an open development project.",
                 "The senior developer reviewed and approved the pull request."),
                ("Merge Conflict", "mɜːrdʒ ˈkɑːnflɪkt",
                 "An event that occurs when Git is unable to automatically resolve differences in code.",
                 "We spent an hour fixing the merge conflict in the main configuration file."),
                ("API", "ˌeɪ piː ˈaɪ",
                 "Application Programming Interface, a way for two or more computer programs to communicate.",
                 "The front-end app fetches user data from the backend API."),
                ("REST", "rest", "Representational State Transfer, a software architectural style.",
                 "The application was built using a standard REST architecture."),
                ("JSON", "ˈdʒeɪsən", "JavaScript Object Notation, a lightweight data-interchange format.",
                 "The server responded with a payload formatted in JSON."),
                ("CI/CD", "ˌsiː aɪ ˌsiː ˈdiː", "Continuous Integration and Continuous Delivery.",
                 "The CI/CD pipeline automatically runs all tests and deploys to production."),
                ("Bug", "bʌɡ", "An error, flaw or fault in a computer program or system.",
                 "We pushed a hotfix to patch the critical bug found in production."),
                ("Refactoring", "riːˈfæktərɪŋ",
                 "The process of restructuring existing computer code without changing its external behavior.",
                 "Refactoring the legacy code made it significantly easier to read and maintain."),
                ("Debugging", "diːˈbʌɡɪŋ",
                 "The process of finding and resolving defects or problems within a computer program.",
                 "She spent the afternoon debugging the memory leak issue."),
                ("Unit Test", "ˈjuːnɪt test",
                 "A software testing method by which individual units of source code are tested.",
                 "Writing a unit test ensures the calculation function continues to work in the future."),
                ("Sprint", "sprɪnt", "A set period of time during which specific work has to be completed.",
                 "We aimed to finish five major features during the current two-week sprint."),
                ("Mockup", "ˈmɑːkʌp", "A scale or full-size model of a design or device.",
                 "The designer provided a mockup of how the new dashboard should look."),
                ("Deployment", "dɪˈplɔɪmənt", "All of the activities that make a software system available for use.",
                 "The Friday evening deployment went smoothly with zero downtime."),
                ("Repo", "ˈriːpoʊ", "Short for repository, a central location in which data is stored and managed.",
                 "Clone the GitHub repo to your local machine to start developing.")
            ],
            "Networking & Security": [
                ("IP Address", "ˌaɪ ˈpiː əˈdres",
                 "A numerical label assigned to each device connected to a computer network.",
                 "The router assigned a dynamic IP address to the new laptop."),
                ("DNS", "ˌdiː en ˈes", "Domain Name System, the phonebook of the Internet.",
                 "DNS translates human-readable names like google.com into IP addresses."),
                ("Router", "ˈraʊtər", "A networking device that forwards data packets between computer networks.",
                 "The core router handles all the traffic leaving the building."),
                ("Switch", "swɪtʃ", "Networking hardware that connects devices on a computer network.",
                 "The 24-port switch connected all the office computers to the local network."),
                ("Firewall", "ˈfaɪərwɔːl",
                 "A network security system that monitors and controls incoming and outgoing network traffic.",
                 "The firewall blocked the malicious connection attempt from an unknown IP."),
                ("Bandwidth", "ˈbændwɪdθ", "The maximum rate of data transfer across a given path.",
                 "Streaming 4K video requires a significant amount of bandwidth."),
                ("Protocol", "ˈproʊtəkɑːl", "A set of rules governing the exchange or transmission of data.",
                 "FTP is a standard network protocol used for the transfer of computer files."),
                ("HTTP", "ˌeɪtʃ tiː tiː ˈpiː",
                 "Hypertext Transfer Protocol, the foundation of data communication for the World Wide Web.",
                 "HTTP traffic is sent in plaintext and can be intercepted easily."),
                ("HTTPS", "ˌeɪtʃ tiː tiː piː ˈes",
                 "An extension of HTTP used for secure communication over a computer network.",
                 "Always ensure a website uses HTTPS before entering your credit card details."),
                ("TCP", "ˌtiː siː ˈpiː",
                 "Transmission Control Protocol, a standard that defines how to establish and maintain a network conversation.",
                 "TCP guarantees the delivery of data packets in the correct order."),
                ("UDP", "ˌjuː diː ˈpiː",
                 "User Datagram Protocol, a communications protocol that is primarily used for establishing low-latency connections.",
                 "Online multiplayer games primarily use UDP to prioritize speed over reliability."),
                ("MAC Address", "mæk əˈdres",
                 "Media Access Control address, a unique identifier assigned to a network interface controller.",
                 "The network administrator filtered access by whitelisting specific MAC addresses."),
                ("Subnet Mask", "ˈsʌbnet mæsk", "A 32-bit number that masks an IP address.",
                 "The subnet mask dictates which portion of the IP address defines the network."),
                ("VPN", "ˌviː piː ˈen", "Virtual Private Network, extends a private network across a public network.",
                 "Employees must connect to the VPN to access internal company servers from home."),
                ("DHCP", "ˌdiː eɪtʃ siː ˈpiː", "Dynamic Host Configuration Protocol, a network management protocol.",
                 "The DHCP server automatically hands out IP addresses to devices as they join."),
                ("Phishing", "ˈfɪʃɪŋ",
                 "The fraudulent attempt to obtain sensitive information by disguising as a trustworthy entity.",
                 "He fell victim to a phishing scam and accidentally gave away his password."),
                ("Encryption", "ɪnˈkrɪpʃən",
                 "The process of encoding a message or information in such a way that only authorized parties can access it.",
                 "End-to-end encryption ensures that no one can read your private messages."),
                ("Malware", "ˈmælwer",
                 "Any software intentionally designed to cause disruption to a computer or server.",
                 "The antivirus software successfully quarantined the incoming malware."),
                ("Penetration Testing", "ˌpenəˈtreɪʃən ˈtestɪŋ",
                 "An authorized simulated cyberattack on a computer system.",
                 "The company hired a security firm to conduct penetration testing on their web app."),
                ("DDoS", "ˈdiːdɑːs", "Distributed Denial of Service, a malicious attempt to disrupt normal traffic.",
                 "The website went offline after being targeted by a massive DDoS attack.")
            ]
        }

        all_words = []
        for t_name, words_list in vocab_data.items():
            topic = Topic(name=t_name, user_id=main_user.id)
            db.session.add(topic)
            db.session.commit()

            for term, ipa, definition, example in words_list:
                word = Word(
                    term=term,
                    ipa=ipa,  # <--- Pass the IPA here!
                    definition=definition,
                    example_sentence=example,
                    topic_id=topic.id,
                    user_id=main_user.id
                )
                db.session.add(word)
                all_words.append(word)

        db.session.commit()

        for word in random.sample(all_words, 25):
            progress = WordProgress(
                user_id=champ.id, word_id=word.id,
                times_tested=5, times_correct=5, is_mastered=True,
                date_mastered=now - timedelta(days=random.randint(0, 3)),
                next_review=now + timedelta(days=30)
            )
            db.session.add(progress)

        for word in random.sample(all_words, 15):
            progress = WordProgress(
                user_id=master.id, word_id=word.id,
                times_tested=4, times_correct=4, is_mastered=True,
                date_mastered=now - timedelta(days=random.randint(0, 3)),
                next_review=now + timedelta(days=30)
            )
            db.session.add(progress)

        java_words = [w for w in all_words if w.topic_id == 1][:5]
        for word in java_words:
            progress = WordProgress(
                user_id=main_user.id, word_id=word.id,
                times_tested=3, times_correct=1,
                next_review=now - timedelta(days=1)
            )
            db.session.add(progress)

        db.session.commit()


if __name__ == '__main__':
    seed_database()